import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";
export const metadata: Metadata = {
  title: "Moksha 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
      <CustomCursor/>
    </html>
  );
}
